#!/bin/bash

# Seeds mongo database
# Expects file Waterloo.csv in the same directory. Ask Greg or Karissa for this file.

mongoimport \
  --host kidsability-shard-0/kidsability-shard-00-00-vswng.mongodb.net:27017,kidsability-shard-00-01-vswng.mongodb.net:27017,kidsability-shard-00-02-vswng.mongodb.net:27017 \
  --ssl \
  --username greg \
  --password kidsability \
  --authenticationDatabase admin \
  --db ClientData \
  --collection KidsAbility \
  --type csv \
  --file ./Waterloo.csv \
  --fields Date,Start,End,Duration,LastName,FirstName,ID,Email,ClientLast,ClientFirst,ClientID,Location,Service,Treatment,Program,ServiceDescription
